project_id = "wtmivgqgvsubgkoyfgwi"

[functions.meta-webhook]
verify_jwt = false

[functions.meta-health]
verify_jwt = true

[functions.meta-send]
verify_jwt = true

[functions.v4-request-password-code]
verify_jwt = false

[functions.v4-verify-password-code]
verify_jwt = false

[functions.v4-reset-password]
verify_jwt = false
