project_id = "wtmivgqgvsubgkoyfgwi"

[functions.meta-webhook]
verify_jwt = false

[functions.meta-health]
verify_jwt = false

[functions.meta-send]
verify_jwt = false

[functions.v4-pin-login]
verify_jwt = false

[functions.v4-pin-logout]
verify_jwt = false

[functions.meta-templates-list]
verify_jwt = false

[functions.meta-templates-create]
verify_jwt = false

[functions.message-contacts-import]
verify_jwt = false
